=== fortnite-music/fortnitebgm-db/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Fortnite music database",
  "description": "Definitive Fortnite music database",
  "type": "array",
  "items": {
    "title": "Fortnite music",
    "type": "object",
    "properties": {
      "decoration": {
        "type": "object",
        "properties": {
          "minorTrack": {
            "description": "Track is a segment of another song",
            "type": "boolean"
          },
          "promoTrack": {
            "description": "Track is from outside the game itself",
            "type": "boolean"
          }
        }
      },
      "description": {
        "description": "Description of the song's usage",
        "type": "string"
      },
      "filename": {
        "type": "string"
      },
      "mark": {
        "description": "Mode icon associated with the song",
        "type": "string"
      },
      "metadata": {
        "type": "object",
        "properties": {
          "albumArtist": {
            "type": "string"
          },
          "artist": {
            "type": "string"
          },
          "subtitle": {
            "description": "Song title from data",
            "type": "string"
          },
          "title": {
            "description": "Official song title",
            "type": "string"
          },
          "year": {
            "type": "string"
          }
        },
        "required": ["albumArtist", "artist", "title", "year"]
      },
      "source": {
        "type": "object",
        "properties": {
          "client": {
            "description": "Client of origin",
            "type": "string"
          },
          "date": {
            "description": "Date of release",
            "type": "string"
          },
          "structure": {
            "description": "Folder structure",
            "type": "string"
          },
          "version": {
            "description": "Version of origin",
            "type": "string"
          }
        },
        "required": ["structure"]
      },
      "youtube": {
        "description": "YouTube video identifier",
        "type": "string"
      }
    },
    "required": [
      "description",
      "filename",
      "mark",
      "metadata",
      "source",
      "youtube"
    ]
  }
}

=== fortnite-music/fortnitebgm-db/bgm/S2.json
[
  {
    "description": "Christmas lobby music",
    "filename": "Holiday_Lobby_Music_2017",
    "mark": "s2",
    "metadata": {
      "albumArtist": "Epic Games",
      "artist": "Epic Games",
      "title": "Holiday Lobby",
      "year": "2017"
    },
    "source": {
      "client": "BR",
      "date": "2017-12-13",
      "structure": "UI",
      "version": "1.11"
    },
    "youtube": "tg28s2id5CA"
  },
  {
    "description": "Christmas Battle Bus music",
    "filename": "SFX_Bus_Flying_XmasMusic_Loop",
    "mark": "s2",
    "metadata": {
      "albumArtist": "Epic Games",
      "artist": "Epic Games",
      "title": "Christmas Battle Bus",
      "year": "2017"
    },
    "source": {
      "client": "BR",
      "date": "2017-12-13",
      "structure": "Extra",
      "version": "1.11"
    },
    "youtube": "5sniVv8_qXE"
  }
]

=== fortnite-music/fortnitebgm-db/bgm/etc/etcTemplate.json
[
  {
    "description": "Track Description",
    "filename": "filename3",
    "mark": "imagetest2",
    "metadata": {
      "albumArtist": "Epic Games",
      "artist": "Artist",
      "title": "Title",
      "year": "2010"
    },
    "source": {
      "structure": "Website"
    },
    "youtube": "GHpl05PmtOs"
  },
  {
    "description": "Used in 'FORTNITE SEASON 5 | ANNOUNCE TRAILER'",
    "filename": "Joywave - Blastoffff",
    "mark": "imagetest4",
    "metadata": {
      "albumArtist": "Joywave",
      "artist": "Joywave",
      "title": "Blastoffff ",
      "year": "2018"
    },
    "source": {
      "structure": "Video"
    },
    "youtube": "qSid2ulDL2Q"
  }
]

=== fortnite-music/fortnitebgm-db/bgm/fortress.json
[
  {
    "description": "Combat?",
    "filename": "breathingtrouble",
    "mark": "fortress",
    "metadata": {
      "albumArtist": "Senking",
      "artist": "Senking",
      "title": "torul",
      "year": "2010"
    },
    "source": {
      "client": "STW",
      "date": "2012-06-22",
      "structure": "Combat",
      "version": "FortressGame"
    },
    "youtube": "RCICBreK_rQ"
  },
  {
    "description": "Daytime Exploration",
    "filename": "deathbydrowning",
    "mark": "fortress",
    "metadata": {
      "albumArtist": "Senking",
      "artist": "Senking",
      "title": "Death by Drowning",
      "year": "2010"
    },
    "source": {
      "client": "STW",
      "date": "2012-06-22",
      "structure": "Area",
      "version": "FortressGame"
    },
    "youtube": "iyd67KQCSmc"
  },
  {
    "description": "Nighttime Exploration",
    "filename": "descentg",
    "mark": "fortress",
    "metadata": {
      "albumArtist": "Scuba",
      "artist": "Scuba",
      "title": "Descent",
      "year": "2010"
    },
    "source": {
      "client": "STW",
      "date": "2012-06-22",
      "structure": "Area",
      "version": "FortressGame"
    },
    "youtube": "FdwHBLeJRyA"
  },
  {
    "description": "Combat?",
    "filename": "eon",
    "mark": "fortress",
    "metadata": {
      "albumArtist": "Lucy",
      "artist": "Lucy",
      "title": "Eon",
      "year": "2011"
    },
    "source": {
      "client": "STW",
      "date": "2012-06-22",
      "structure": "Combat",
      "version": "FortressGame"
    },
    "youtube": "lQMY9Yv65bw"
  },
  {
    "description": "Combat?",
    "filename": "gas",
    "mark": "fortress",
    "metadata": {
      "albumArtist": "Lucy",
      "artist": "Lucy",
      "title": "gas",
      "year": "2011"
    },
    "source": {
      "client": "STW",
      "date": "2012-06-22",
      "structure": "Combat",
      "version": "FortressGame"
    },
    "youtube": "gArTLmH9fxA"
  },
  {
    "description": "Daytime Exploration",
    "filename": "lowflow",
    "mark": "fortress",
    "metadata": {
      "albumArtist": "Senking",
      "artist": "Senking",
      "title": "Low Flow",
      "year": "2010"
    },
    "source": {
      "client": "STW",
      "date": "2012-06-22",
      "structure": "Area",
      "version": "FortressGame"
    },
    "youtube": "7a54Ha1B58Q"
  },
  {
    "description": "Exploration?",
    "filename": "luma",
    "mark": "fortress",
    "metadata": {
      "albumArtist": "Senking",
      "artist": "Senking",
      "title": "Luma",
      "year": "2010"
    },
    "source": {
      "client": "STW",
      "date": "2012-06-22",
      "structure": "Combat",
      "version": "FortressGame"
    },
    "youtube": "06z_H-iASUQ"
  },
  {
    "description": "Combat",
    "filename": "newcombat",
    "mark": "fortress",
    "metadata": {
      "albumArtist": "Kangding Ray",
      "artist": "Kangding Ray",
      "title": "OR / 'New Combat'",
      "year": "2011"
    },
    "source": {
      "client": "STW",
      "date": "2012-06-22",
      "structure": "Combat",
      "version": "FortressGame"
    },
    "youtube": "w84PKh8DyOU"
  },
  {
    "description": "Morning Exploration",
    "filename": "torul",
    "mark": "fortress",
    "metadata": {
      "albumArtist": "Lucy",
      "artist": "Lucy",
      "title": "torul",
      "year": "2011"
    },
    "source": {
      "client": "STW",
      "date": "2012-06-22",
      "structure": "Area",
      "version": "FortressGame"
    },
    "youtube": "l-t6AzOfjMk"
  },
  {
    "description": "Exploration?",
    "filename": "unlighted",
    "mark": "fortress",
    "metadata": {
      "albumArtist": "Senking",
      "artist": "Senking",
      "title": "Unlighted",
      "year": "2010"
    },
    "source": {
      "client": "STW",
      "date": "2012-06-22",
      "structure": "Combat",
      "version": "FortressGame"
    },
    "youtube": "QxsL3PaR-iU"
  }
]

=== fortnite-music/fortnitebgm-db/file-sorted.json
[
  {
    "description": "'Help Ramirez' ending cutscene",
    "filename": "Fort_Cine_Onboarding_Rocket",
    "mark": "alpha",
    "metadata": {
      "albumArtist": "Epic Games",
      "artist": "Rom Di Prisco",
      "title": "Rocket Cutscene",
      "year": "2015"
    },
    "source": {
      "client": "STW",
      "date": "2015-12-09",
      "structure": "Cutscene",
      "version": "Online Test 6"
    },
    "youtube": "qA6hIlQob6A"
  },
  {
    "description": "Viewing mission rewards",
    "filename": "fort_rewardscreen_Music_Intro",
    "mark": "alpha",
    "metadata": {
      "albumArtist": "Epic Games",
      "artist": "Rom Di Prisco",
      "title": "Reward Screen",
      "year": "2016"
    },
    "source": {
      "client": "STW",
      "date": "2016-07-25",
      "structure": "UI",
      "version": "Online Test 8"
    },
    "youtube": "OMPEPoQZch8"
  },
  {
    "description": "viewing mission rewards",
    "filename": "fort_rewardscreen_Music_SecondLoopFix",
    "mark": "alpha",
    "metadata": {
      "albumArtist": "Epic Games",
      "artist": "Rom Di Prisco",
      "title": "Reward Screen (Second Loop)",
      "year": "2016"
    },
    "source": {
      "client": "STW",
      "date": "2016-07-25",
      "structure": "UI",
      "version": "Online Test 8"
    },
    "youtube": "EDSiv7Ufa9E"
  },
  {
    "description": "Viewing Squads or Skill Tree",
    "filename": "fortnite_daytime_music_positive_one",
    "mark": "alpha",
    "metadata": {
      "albumArtist": "Epic Games",
      "artist": "Rom Di Prisco",
      "title": "Squads / Skill Tree",
      "year": "2014"
    },
    "source": {
      "client": "STW",
      "date": "2014-12-02",
      "structure": "UI",
      "version": "Online Test 1"
    },
    "youtube": "5ZvRcg-lPMc"
  },
  {
    "description": "Setting up Homebase",
    "filename": "fortnite_daytime_music_positive_two",
    "mark": "alpha",
    "metadata": {
      "albumArtist": "Epic Games",
      "artist": "Rom Di Prisco",
      "title": "Naming Your Homebase",
      "year": "2014"
    },
    "source": {
      "client": "STW",
      "date": "2014-12-02",
      "structure": "UI",
      "version": "Online Test 1"
    },
    "youtube": "czUd84sEV-g"
  },
  {
    "description": "Viewing Homebase and quests",
    "filename": "fortnite_homebase_music_loop",
    "mark": "alpha",
    "metadata": {
      "albumArtist": "Epic Games",
      "artist": "Rom Di Prisco",
      "title": "Homebase",
      "year": "2014"
    },
    "source": {
      "client": "STW",
      "date": "2014-12-02",
      "structure": "UI",
      "version": "Online Test 1"
    },
    "youtube": "QA3baa8cucI"
  },
  {
    "description": "Login Screen before v3.00",
    "filename": "fortnite_login_screen",
    "mark": "alpha",
    "metadata": {
      "albumArtist": "Epic Games",
      "artist": "Rom Di Prisco",
      "title": "Login Screen",
      "year": "2014"
    },
    "source": {
      "client": "STW",
      "date": "2014-12-02",
      "structure": "UI",
      "version": "Online Test 1"
    },
    "youtube": "g-I0l-LH77s"
  },
  {
    "description": "'Help Ramirez' combat track",
    "filename": "fortnite_onboarding_cave_action",
    "mark": "alpha",
    "metadata": {
      "albumArtist": "Epic Games",
      "artist": "Rom Di Prisco",
      "title": "Cave Action",
      "year": "2015"
    },
    "source": {
      "client": "STW",
      "date": "2015-12-09",
      "structure": "Combat",
      "version": "Online Test 6"
    },
    "youtube": "aitAk7JgI_o"
  },
  {
    "description": "'Help Ramirez' background music",
    "filename": "fortnite_onboarding_cave_music",
    "mark": "alpha",
    "metadata": {
      "albumArtist": "Epic Games",
      "artist": "Rom Di Prisco",
      "title": "Cave Exploration",
      "year": "2015"
    },
    "source": {
      "client": "STW",
      "date": "2015-12-09",
      "structure": "Area",
      "version": "Online Test 6"
    },
    "youtube": "OVV2Kd3mehA"
  },
  {
    "description": "Viewing Loot Llamas",
    "filename": "llamaopen",
    "mark": "alpha",
    "metadata": {
      "albumArtist": "Epic Games",
      "artist": "Rom Di Prisco",
      "title": "Loot Llama (Alpha)",
      "year": "2015"
    },
    "source": {
      "client": "STW",
      "date": "2015-09-29",
      "structure": "UI",
      "version": "Online Test 5"
    },
    "youtube": "4AfN_eWN2g8"
  },
  {
    "description": "Opening Loot Llamas",
    "filename": "new_victory_loop",
    "mark": "alpha",
    "metadata": {
      "albumArtist": "Epic Games",
      "artist": "Rom Di Prisco",
      "title": "Llama Rewards",
      "year": "2015"
    },
    "source": {
      "client": "STW",
      "date": "2015-09-29",
      "structure": "UI",
      "version": "Online Test 5"
    },
    "youtube": "M29n6lF9Yz8"
  },
  {
    "description": "'Help Ramirez' combat track",
    "filename": "Onboarding_Combat_Loop",
    "mark": "alpha",
    "metadata": {
      "albumArtist": "Epic Games",
      "artist": "Rom Di Prisco",
      "title": "Combat Alt",
      "year": "2015"
    },
    "source": {
      "client": "STW",
      "date": "2015-12-09",
      "structure": "Combat",
      "version": "Online Test 6"
    },
    "youtube": "rfeaZ36do5A"
  },
  {
    "description": "'Help Ramirez' quest ending track",
    "filename": "Onboarding_CountDown_Music",
    "mark": "alpha",
    "metadata": {
      "albumArtist": "Epic Games",
      "artist": "Rom Di Prisco",
      "title": "Countdown",
      "year": "2015"
    },
    "source": {
      "client": "STW",
      "date": "2015-12-09",
      "structure": "Cutscene",
      "version": "Online Test 6"
    },
    "youtube": "XmLxKm64h9k"
  },
  {
    "description": "'Help Ramirez' combat track",
    "filename": "onboarding_high_combat_loop",
    "mark": "alpha",
    "metadata": {
      "albumArtist": "Epic Games",
      "artist": "Rom Di Prisco",
      "title": "High Combat",
      "year": "2016"
    },
    "source": {
      "client": "STW",
      "date": "2016-07-25",
      "structure": "Combat",
      "version": "Online Test 8"
    },
    "youtube": "4GWWYIq0fI4"
  },
  {
    "description": "Save The World Intro Cinematic",
    "filename": "onboarding_intro_TEMP_CINE_introrender",
    "mark": "alpha",
    "metadata": {
      "albumArtist": "Epic Games",
      "artist": "Rom Di Prisco",
      "title": "Intro Cinematic",
      "year": "2016"
    },
    "source": {
      "client": "STW",
      "date": "2016-07-25",
      "structure": "Cutscene",
      "version": "Online Test 8"
    },
    "youtube": "1RYdtvEKU5s"
  },
  {
    "description": "'Help Ramirez' combat track",
    "filename": "Onboarding_Main_Combat_Loop",
    "mark": "alpha",
    "metadata": {
      "albumArtist": "Epic Games",
      "artist": "Rom Di Prisco",
      "title": "Combat",
      "year": "2015"
    },
    "source": {
      "client": "STW",
      "date": "2015-12-09",
      "structure": "Combat",
      "version": "Online Test 6"
    },
    "youtube": "JtX3aJhOQCc"
  },
  {
    "description": "'Help Ramirez' opening cutscene",
    "filename": "Onboarding_Ramirez_SFX_Music_VO_03",
    "mark": "alpha",
    "metadata": {
      "albumArtist": "Epic Games",
      "artist": "Epic Games",
      "title": "Ramirez Cutscene",
      "year": "2016"
    },
    "source": {
      "client": "STW",
      "date": "2016-07-25",
      "structure": "Cutscene",
      "version": "Online Test 8"
    },
    "youtube": "5z8mHQBDMk4"
  },
  {
    "description": "Finding the rocket in 'Help Ramirez'",
    "filename": "onboarding_rocket_room_loop",
    "mark": "alpha",
    "metadata": {
      "albumArtist": "Epic Games",
      "artist": "Rom Di Prisco",
      "title": "Rocket Room",
      "year": "2016"
    },
    "source": {
      "client": "STW",
      "date": "2016-07-25",
      "structure": "Area",
      "version": "Online Test 8"
    },
    "youtube": "agwyTRjtAOo"
  },
  {
    "description": "Protecting the rocket in 'Help Ramirez'",
    "filename": "rocket_tension_loop",
    "mark": "alpha",
    "metadata": {
      "albumArtist": "Epic Games",
      "artist": "Rom Di Prisco",
      "title": "Rocket Tension",
      "year": "2016"
    },
    "source": {
      "client": "STW",
      "date": "2016-07-25",
      "structure": "Combat",
      "version": "Online Test 8"
    },
    "youtube": "GSh4cNo7GGo"
  },
  {
    "description": "Viewing the Vault or Vindertech Store",
    "filename": "vindertech store v2",
    "mark": "alpha",
    "metadata": {
      "albumArtist": "Epic Games",
      "artist": "Rom Di Prisco",
      "title": "Vault / Vindertech Store (Alpha)",
      "year": "2015"
    },
    "source": {
      "client": "STW",
      "date": "2015-09-29",
      "structure": "UI",
      "version": "Online Test 5"
    },
    "youtube": "XBLWSBGIPOY"
  },
  {
    "description": "Viewing the World Map",
    "filename": "world_map_overview_music_a",
    "mark": "alpha",
    "metadata": {
      "albumArtist": "Epic Games",
      "artist": "Rom Di Prisco",
      "title": "World Map",
      "year": "2015"
    },
    "source": {
      "client": "STW",
      "date": "2015-06-29",
      "structure": "UI",
      "version": "Online Test 3"
    },
    "youtube": "ciUr5OX4WRY"
  }
]

=== fortnite-music/fortnitebgm-db/bgm/SW.json
[
  {
    "description": "Stonewood Combat",
    "filename": "Combat_High_Threat_Main_Loop",
    "mark": "base",
    "metadata": {
      "albumArtist": "Epic Games",
      "artist": "Epic Games",
      "title": "High Combat (Stonewood)",
      "year": "2018"
    },
    "source": {
      "client": "STW",
      "date": "2018-02-21",
      "structure": "Combat",
      "version": "3.0.0"
    },
    "youtube": "BjEMO63m7dE"
  },
  {
    "description": "Stonewood Combat",
    "filename": "Combat_High_Threat_StctPerc_Short_Loop",
    "mark": "base",
    "metadata": {
      "albumArtist": "Epic Games",
      "artist": "Epic Games",
      "title": "High Combat (Short, Stonewood)",
      "year": "2018"
    },
    "source": {
      "client": "STW",
      "date": "2018-02-21",
      "structure": "Combat",
      "version": "3.0.0"
    },
    "youtube": "ckVB6uBeWLM"
  },
  {
    "description": "Stonewood Combat",
    "filename": "Combat_Low_Threat_Loop",
    "mark": "base",
    "metadata": {
      "albumArtist": "Epic Games",
      "artist": "Epic Games",
      "title": "Low Combat (Stonewood)",
      "year": "2018"
    },
    "source": {
      "client": "STW",
      "date": "2018-02-21",
      "structure": "Combat",
      "version": "3.0.0"
    },
    "youtube": "5tOYc2HEPRo"
  },
  {
    "description": "Stonewood Combat",
    "filename": "Combat_Med_Threat_Alt_01_Loop",
    "mark": "base",
    "metadata": {
      "albumArtist": "Epic Games",
      "artist": "Epic Games",
      "title": "Medium Combat (Alt 1, Stonewood)",
      "year": "2018"
    },
    "source": {
      "client": "STW",
      "date": "2018-02-21",
      "structure": "Combat",
      "version": "3.0.0"
    },
    "youtube": "vAGW6iG-vsY"
  },
  {
    "description": "Stonewood Combat",
    "filename": "Combat_Med_Threat_Alt_02_Loop",
    "mark": "base",
    "metadata": {
      "albumArtist": "Epic Games",
      "artist": "Epic Games",
      "title": "Medium Combat (Alt 2, Stonewood)",
      "year": "2018"
    },
    "source": {
      "client": "STW",
      "date": "2018-02-21",
      "structure": "Combat",
      "version": "3.0.0"
    },
    "youtube": "aZB0SC7xelE"
  },
  {
    "description": "Stonewood Combat",
    "filename": "Combat_Med_Threat_Alt_03_Loop",
    "mark": "base",
    "metadata": {
      "albumArtist": "Epic Games",
      "artist": "Epic Games",
      "title": "Medium Combat (Alt 3, Stonewood)",
      "year": "2018"
    },
    "source": {
      "client": "STW",
      "date": "2018-02-21",
      "structure": "Combat",
      "version": "3.0.0"
    },
    "youtube": "gK0f6dA3IEM"
  },
  {
    "description": "Stonewood Combat",
    "filename": "Combat_Med_Threat_Loop",
    "mark": "base",
    "metadata": {
      "albumArtist": "Epic Games",
      "artist": "Epic Games",
      "title": "Medium Combat (Stonewood)",
      "year": "2018"
    },
    "source": {
      "client": "STW",
      "date": "2018-02-21",
      "structure": "Combat",
      "version": "3.0.0"
    },
    "youtube": "X0SBg6gHuGk"
  },
  {
    "description": "Stonewood Combat",
    "filename": "Combat_Med_Threat_Subdued_Loop",
    "mark": "base",
    "metadata": {
      "albumArtist": "Epic Games",
      "artist": "Epic Games",
      "title": "Medium Combat (Subdued, Stonewood)",
      "year": "2018"
    },
    "source": {
      "client": "STW",
      "date": "2018-02-21",
      "structure": "Combat",
      "version": "3.0.0"
    },
    "youtube": "FAON5n9Ecj0"
  },
  {
    "description": "Stonewood Combat",
    "filename": "Combat_Very_High_Threat_Main_Loop",
    "mark": "base",
    "metadata": {
      "albumArtist": "Epic Games",
      "artist": "Epic Games",
      "title": "Very High Combat (Stonewood)",
      "year": "2018"
    },
    "source": {
      "client": "STW",
      "date": "2018-02-21",
      "structure": "Combat",
      "version": "3.0.0"
    },
    "youtube": "WbM8aNTAHag"
  },
  {
    "description": "Stonewood Exploration",
    "filename": "Exploring_Dawn_Morning_V2_Loop",
    "mark": "base",
    "metadata": {
      "albumArtist": "Epic Games",
      "artist": "Epic Games",
      "title": "Morning Exploration (Stonewood)",
      "year": "2018"
    },
    "source": {
      "client": "STW",
      "date": "2018-02-21",
      "structure": "Area",
      "version": "3.0.0"
    },
    "youtube": "I3PRrzcmWVw"
  },
  {
    "description": "Stonewood Exploration",
    "filename": "Exploring_Day_V2_Loop",
    "mark": "base",
    "metadata": {
      "albumArtist": "Epic Games",
      "artist": "Epic Games",
      "title": "Day Exploration (Stonewood)",
      "year": "2018"
    },
    "source": {
      "client": "STW",
      "date": "2018-02-21",
      "structure": "Area",
      "version": "3.0.0"
    },
    "youtube": "m-6f-1f64N0"
  },
  {
    "description": "Stonewood Exploration",
    "filename": "Exploring_DuskLoop",
    "mark": "base",
    "metadata": {
      "albumArtist": "Epic Games",
      "artist": "Epic Games",
      "title": "Dusk Exploration (Stonewood)",
      "year": "2018"
    },
    "source": {
      "client": "STW",
      "date": "2018-02-21",
      "structure": "Area",
      "version": "3.0.0"
    },
    "youtube": "4TxzgRHa5n4"
  },
  {
    "description": "Stonewood Exploration",
    "filename": "Exploring_General_Day_V2_Loop",
    "mark": "base",
    "metadata": {
      "albumArtist": "Epic Games",
      "artist": "Epic Games",
      "title": "Day Exploration (Alt, Stonewood)",
      "year": "2018"
    },
    "source": {
      "client": "STW",
      "date": "2018-02-21",
      "structure": "Area",
      "version": "3.0.0"
    },
    "youtube": "BFkaQZ0pYDE"
  },
  {
    "description": "Stonewood Exploration",
    "filename": "Exploring_Night_Loop",
    "mark": "base",
    "metadata": {
      "albumArtist": "Epic Games",
      "artist": "Epic Games",
      "title": "Night Exploration (Stonewood)",
      "year": "2018"
    },
    "source": {
      "client": "STW",
      "date": "2018-02-21",
      "structure": "Area",
      "version": "3.0.0"
    },
    "youtube": "ONkEEHzehWE"
  },
  {
    "description": "Stonewood Exploration",
    "filename": "Exploring_Rural_Day_Loop",
    "mark": "base",
    "metadata": {
      "albumArtist": "Epic Games",
      "artist": "Epic Games",
      "title": "Rural Exploration (Stonewood)",
      "year": "2018"
    },
    "source": {
      "client": "STW",
      "date": "2018-02-21",
      "structure": "Area",
      "version": "3.0.0"
    },
    "youtube": "OYFRYwVVo6E"
  }
]

=== fortnite-music/fortnitebgm-db/bgm/S1.json
[
  {
    "description": "Lobby music until Season 3",
    "filename": "fort_lobby_music_athena",
    "mark": "s1",
    "metadata": {
      "albumArtist": "Epic Games",
      "artist": "Epic Games",
      "title": "OG (Classic)",
      "year": "2017"
    },
    "source": {
      "client": "STW",
      "date": "2017-09-12",
      "structure": "UI",
      "version": "1.6.0"
    },
    "youtube": "fQ1uau2Ep34"
  },
  {
    "description": "Battle Bus music",
    "filename": "SFX_Bus_Flying_PartyMusic_Loop",
    "mark": "s1",
    "metadata": {
      "albumArtist": "Epic Games",
      "artist": "Epic Games",
      "title": "Battle Bus music",
      "year": "2017"
    },
    "source": {
      "client": "STW",
      "date": "2017-09-12",
      "structure": "Extra",
      "version": "1.6.0"
    },
    "youtube": "vQbw_wpVUMY"
  }
]

=== fortnite-music/fortnitebgm-db/bgm/FNTemplate.json
[
  {
    "description": "Track Description",
    "filename": "filename1",
    "mark": "imagetest",
    "metadata": {
      "albumArtist": "Epic Games",
      "artist": "Artist",
      "title": "Title",
      "year": "2010"
    },
    "source": {
      "client": "C1S1",
      "date": "2010-01-01",
      "structure": "FolderName",
      "version": "1.00"
    },
    "youtube": "dwlGJS1b08g"
  },
  {
    "decoration": {
      "minorTrack": true
    },
    "description": "Track Description",
    "filename": "filename2",
    "mark": "imagetest",
    "metadata": {
      "albumArtist": "Epic Games",
      "artist": "Artist",
      "title": "Title2",
      "titleAlt": "Alt Title2",
      "year": "2010"
    },
    "source": {
      "structure": "Website"
    },
    "youtube": "w9FJhoIyLqs"
  }
]

=== fortnite-music/fortnitebgm-db/bgm/S3.json
[
  {
    "description": "Lobby Music from Season 3 to Chapter 3 Season 1",
    "filename": "BR_Lobby_Music_Loop",
    "mark": "s3",
    "metadata": {
      "albumArtist": "Epic Games",
      "artist": "Epic Games",
      "title": "Lobby Classic",
      "year": "2018"
    },
    "source": {
      "client": "BR",
      "date": "2018-02-21",
      "structure": "UI",
      "version": "3.0.0"
    },
    "youtube": "O2bnHN-GtM0"
  }
]
