=== fortnite-music/fortnitebgm-db/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Fortnite music database",
  "description": "Definitive Fortnite music database",
  "type": "array",
  "items": {
    "title": "Fortnite music",
    "type": "object",
    "properties": {
      "decoration": {
        "type": "object",
        "properties": {
          "minorTrack": {
            "description": "Track is a segment of another song",
            "type": "boolean"
          },
          "promoTrack": {
            "description": "Track is from outside the game itself",
            "type": "boolean"
          }
        }
      },
      "description": {
        "description": "Description of the song's usage",
        "type": "string"
      },
      "filename": {
        "type": "string"
      },
      "mark": {
        "description": "Mode icon associated with the song",
        "type": "string"
      },
      "metadata": {
        "type": "object",
        "properties": {
          "albumArtist": {
            "type": "string"
          },
          "artist": {
            "type": "string"
          },
          "subtitle": {
            "description": "Song title from data",
            "type": "string"
          },
          "title": {
            "description": "Official song title",
            "type": "string"
          },
          "year": {
            "type": "string"
          }
        },
        "required": ["albumArtist", "artist", "title", "year"]
      },
      "source": {
        "type": "object",
        "properties": {
          "client": {
            "description": "Client of origin",
            "type": "string"
          },
          "date": {
            "description": "Date of release",
            "type": "string"
          },
          "structure": {
            "description": "Folder structure",
            "type": "string"
          },
          "version": {
            "description": "Version of origin",
            "type": "string"
          }
        },
        "required": ["structure"]
      },
      "youtube": {
        "description": "YouTube video identifier",
        "type": "string"
      }
    },
    "required": [
      "description",
      "filename",
      "mark",
      "metadata",
      "source",
      "youtube"
    ]
  }
}

=== fortnite-music/fortnitebgm-db/bgm/base.json
[
    {
        "description": "Background music when viewing mission rewards",
        "filename": "fort_rewardscreen_Music_Intro",
        "mark": "base",
        "metadata": {
            "albumArtist": "Epic Games",
            "artist": "Rom Di Prisco",
            "title": "Homebase",
            "year": "2015"
        },
        "source": {
            "client": "STW",
            "date": "2015-12-02",
            "structure": "UI",
            "version": "Online Test"
        },
        "youtube": "OMPEPoQZch8"
    },
    {
        "description": "Alt music when viewing mission rewards",
        "filename": "fort_rewardscreen_Music_SecondLoopFix",
        "mark": "base",
        "metadata": {
            "albumArtist": "Epic Games",
            "artist": "Rom Di Prisco",
            "title": "Homebase",
            "year": "2015"
        },
        "source": {
            "client": "STW",
            "date": "2015-12-02",
            "structure": "UI",
            "version": "Online Test"
        },
        "youtube": "EDSiv7Ufa9E"
    }
]

=== fortnite-music/fortnitebgm-db/bgm/OT.json
[
  {
    "description": "Combat track during mission",
    "filename": "fort_action_high_layer",
    "mark": "missing",
    "metadata": {
      "albumArtist": "Epic Games",
      "artist": "Epic Games",
      "title": "Action High Layer",
      "year": "2014"
    },
    "source": {
        "client": "STW",
        "structure": "Combat",
        "date": "2014",
        "version": "Online Test"
    },
    "youtube": "F6zJ2urQQWc"
  },
  {
    "description": "Login Screen before v3.00",
    "filename": "fortnite_login_screen",
    "mark": "missing",
    "metadata": {
      "albumArtist": "Epic Games",
      "artist": "Rom Di Prisco",
      "title": "Login Screen",
      "year": "2014"
    },
    "source": {
      "client": "STW",
      "structure": "UI",
      "date": "2014",
      "version": "Online Test"
    },
    "youtube": "g-I0l-LH77s"
  }
]

=== fortnite-music/fortnitebgm-db/bgm/etc/trailer.json
[
  {
    "description": "Used in 'Fortnite Experience Trailer'",
    "filename": "EcstaticSteps",
    "mark": "media",
    "metadata": {
      "albumArtist": "Various Artists",
      "artist": "Bustafunk",
      "title": "Ecstatic Steps",
      "year": "2013"
    },
    "source": {
      "client": "YT",
      "structure": "Trailer",
      "date": "2014-12-01"
    },
    "youtube": "gD8DYVmA6FI"
  },
  {
    "description": "Used in 'FORTNITE SEASON 5 | ANNOUNCE TRAILER'",
    "filename": "JoywaveBlastoffff",
    "mark": "media",
    "metadata": {
      "albumArtist": "Joywave",
      "artist": "Joywave",
      "title": "Blastoffff",
      "year": "2018"
    },
    "source": {
      "client": "YT",
      "structure": "Trailer",
      "date": "2018-07-12"
    },
    "youtube": "qSid2ulDL2Q"
  }
]
